# Generated by Django 5.0.6 on 2025-12-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=25, null=True)),
                ('password', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'UserInfo',
            },
        ),
    ]
