# Generated by Django 5.0.6 on 2025-12-15 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_orderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='card_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 20, 17, 2, 23, 199787)),
        ),
    ]
