# Generated by Django 5.0.6 on 2025-12-15 11:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_orderhistory_card_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.userinfo'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 20, 17, 4, 17, 682001)),
        ),
    ]
