# Generated by Django 5.0.6 on 2025-12-15 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_orderhistory_user_alter_orderhistory_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 20, 17, 25, 38, 760969)),
        ),
    ]
