# Generated by Django 5.0.6 on 2025-12-15 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_orderhistory_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 20, 17, 33, 12, 688610)),
        ),
    ]
