# Generated by Django 5.0.6 on 2025-12-16 10:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_alter_orderhistory_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 21, 16, 3, 32, 997386)),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.mycart'),
        ),
    ]
