# Generated by Django 5.0.6 on 2026-01-11 12:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_carddetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddetails',
            name='id',
        ),
        migrations.AddField(
            model_name='carddetails',
            name='order_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.orderhistory'),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='card_no',
            field=models.IntegerField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 16, 18, 11, 42, 225675)),
        ),
    ]
