# Generated by Django 5.0.6 on 2026-01-11 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0012_remove_carddetails_id_carddetails_order_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carddetails',
            old_name='order_date',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 16, 18, 12, 25, 723234)),
        ),
    ]
