# Generated by Django 5.0.6 on 2026-01-11 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0013_rename_order_date_carddetails_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddetails',
            name='order',
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 16, 18, 20, 27, 591919)),
        ),
    ]
