# Generated by Django 5.0.6 on 2026-01-11 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0015_alter_orderhistory_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 16, 18, 29, 13, 786042)),
        ),
        migrations.DeleteModel(
            name='CardDetails',
        ),
    ]
