# Generated by Django 5.0.6 on 2026-01-11 12:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0016_alter_orderhistory_delivery_date_delete_carddetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 16, 18, 29, 26, 355894)),
        ),
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.IntegerField(max_length=12, unique=True)),
                ('cvv', models.IntegerField(max_length=3, null=True)),
                ('expiry_date', models.CharField(max_length=7, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.userinfo')),
            ],
            options={
                'db_table': 'Card Details',
            },
        ),
    ]
