# Generated by Django 5.0.6 on 2026-01-12 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0017_alter_orderhistory_delivery_date_carddetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetails',
            name='card_no',
            field=models.IntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 17, 18, 9, 47, 373859)),
        ),
    ]
